[target.aarch64-unknown-linux-musl]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/ld.lld", "-C", "link-arg=--target=aarch64-unknown-linux-musl"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=/usr/bin/ld.lld", "-C", "link-arg=--target=aarch64-unknown-linux-gnu"]

[target.arm-unknown-linux-gnueabi]
linker = "arm-linux-gnueabi-gcc"
