name: artifacts

on:
  workflow_dispatch:
  push:
    branches:
      - actions
    # only run if there are changes in the source code
    # or if this file is changed
    paths:
      - 'src/**'
      - '.github/workflows/artifacts.yml'
jobs:
  ubuntu_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu_x86
          path: target/release/scode

  push_artifacts:
    needs: [ubuntu_x86]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: artifacts

      - uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: Upload artifacts
        run: |
          git status
          ls -l
          ls -l artifacts || true
          CHANGES=$(git diff --name-only)
          if [ -n "$CHANGES" ]; then
            echo "Changes detected"
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add artifacts
            git commit -m "action: add artifacts"
            git push origin HEAD:artifacts --follow-tags
          else
            echo "No changes detected"
            exit 0
          fi
          git status
