name: Make

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  macos_arm:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: aarch64-apple-darwin
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target aarch64-apple-darwin
    - run: bash codesign.sh "aarch64-apple-darwin/release"
    - uses: actions/upload-artifact@v2
      with:
        name: macos_arm
        path: target/aarch64-apple-darwin/release/scode

  macos_x86:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - run: bash codesign.sh "release"
    - uses: actions/upload-artifact@v2
      with:
        name: macos_x86
        path: target/release/scode

  windows_x86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: x86_64-pc-windows-msvc
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v2
      with:
        name: windows_x86
        path: target/x86_64-pc-windows-msvc/release/scode.exe

  windows_arm:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: aarch64-pc-windows-msvc
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target aarch64-pc-windows-msvc
    - uses: actions/upload-artifact@v2
      with:
        name: windows_arm
        path: target/aarch64-pc-windows-msvc/release/scode.exe

  ubuntu_x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu_x86
        path: target/release/scode

  ubuntu_arm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        # target: aarch64-unknown-linux-gnu
        target: gcc-aarch64-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: build
        # args: --release --target aarch64-unknown-linux-gnu
        args: --release --target gcc-aarch64-linux-gnu
    - uses: actions/upload-artifact@v2
      with:
        name: ubuntu_arm
        # path: target/aarch64-unknown-linux-gnu/release/scode
        path: target/gcc-aarch64-linux-gnu/release/scode


        # {target: "aarch64-unknown-linux-gnu", os: "ubuntu-latest", name: "linux_arm"},
        # {target: "x86_64-unknown-linux-gnu", os: "ubuntu-latest", name: "linux_x86"},
        # {target: "x86_64-apple-darwin", os: "macos-latest", name: "macos_x86"},
        # {target: "aarch64-apple-darwin", os: "macos-latest-xlarge", name: "macos_arm"},
        # {target: "x86_64-pc-windows-msvc", os: "windows-latest", name: "windows_x86"},
        # {target: "aarch64-pc-windows-msvc", os: "windows-latest", name: "windows_arm"}

  combine_artifacts:
    needs: [macos_arm, macos_x86, windows_x86, windows_arm, ubuntu_x86, ubuntu_arm]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: combined_artifacts/

      - name: Zip artifacts
        run: |
          zip -r artifacts.zip artifacts/

      - name: Upload combined artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip
