name: Make

on:
  workflow_dispatch:
  push:
    branches:
      - actions

jobs:
  ubuntu_x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu_x86
          path: target/release/scode

  combine_artifacts:
    needs: [ubuntu_x86]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}


      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts/

      - name: Zip artifacts
        run: zip -r artifacts.zip artifacts/

      - name: Upload combined artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts.zip

      - name: Generate Tag Name
        run: echo "TAG_NAME=$(date +v%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Create and Push Tag if Not Exists
        run: |
          if ! git rev-parse $TAG_NAME >/dev/null 2>&1; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git tag $TAG_NAME
            git push origin $TAG_NAME
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
