name: Make

on:
  push:
    branches:
      - ubuntu-arm
  workflow_dispatch:

jobs:
  ubuntu_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: arm-unknown-linux-gnueabi
          override: true
      - name: Install ARM GCC
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target arm-unknown-linux-gnueabi
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu_arm
          path: target/arm-unknown-linux-gnueabi/release/scode
