name: publish

## Runs when the version workflow completes or manually triggered
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["version"]
    types:
      - completed

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Print version
        run: |
          echo "Package version:"
          node -p "require('./package.json').version"

      - name: Checkout artifacts branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: artifacts
          path: artifacts

      - name: Copy artifacts
        run: |
          echo "Copying build artifacts..."
          cp -R artifacts/artifacts ./artifacts

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          VERSION=$(node -p "require('./package.json').version")

          echo "Publishing version: $VERSION"
          if [[ "$VERSION" == *-* ]]; then
            echo "Detected prerelease → publishing with tag 'alpha'"
            npm publish --tag alpha
          else
            echo "Detected stable release → publishing with tag 'latest'"
            npm publish --access=public --tag latest
          fi
