name: publish

## This will run when the the version is updated
## It will then pull the artifacts from the artifacts branch
## and then publish the package to npm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["version"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: Fetch artifacts branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin artifacts:artifacts
          git checkout artifacts -- artifacts

      - name: Package
        run: |
          npm pack

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: "*.tgz"

      - name: Publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo "Checking if non-prerelease version"
          if [[ $(node -p "require('./package.json').version") != *-* ]]; then
            echo "Publishing Latest"
            echo "npm publish --tag latest"
          else
            echo "Publishing Next"
            echo "npm publish --tag next"
          fi

      # - name: Deploy example page
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     echo "Deploying example page"
      #     cd example
      #     npm install
      #     npm publish
