name: publish

## This will run when the artifact branch is pushed to
## Meaning when the binaries have been updated and pushed to the artifacts branch
## It will then pull the artifacts branch and then publish the package to npm

on:
  workflow_dispatch:
  push:
    branches:
      - artifacts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '20'

      - name: Pull the artifacts
        run: |
          git checkout origin/artifacts -- artifacts
          git status
          ls -l
          ls -l artifacts
