name: publish

## This will run when the the version is updated
## It will then pull the artifacts from the artifacts branch
## and then publish the package to npm

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["version"]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 0

      - name: VERSION
        run: |
          echo $(node -p "require('./package.json').version")

      - name: Fetch artifacts branch
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin artifacts:artifacts
          git checkout artifacts -- artifacts

      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: |
          echo "Checking if non-prerelease version"
          if [[ $(node -p "require('./package.json').version") == *-* ]]; then
            echo "Publishing Alpha"
            npm publish --tag alpha
          else
            echo "Publishing Latest"
            npm publish --access=public --tag latest
          fi
